stages:
    - check
    - release

shellcheck:
    stage: check
    image: koalaman/shellcheck-alpine:stable
    script: shellcheck mx

release:
    stage: release
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    script: echo 'Releasing $CI_COMMIT_TAG'
    release:
        tag_name: $CI_COMMIT_TAG
        description: CHANGELOG.md
